/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TankersRouteImport } from './routes/tankers'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as BookTankerRouteImport } from './routes/book-tanker'
import { Route as IndexRouteImport } from './routes/index'

const TankersRoute = TankersRouteImport.update({
  id: '/tankers',
  path: '/tankers',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTankerRoute = BookTankerRouteImport.update({
  id: '/book-tanker',
  path: '/book-tanker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-tanker': typeof BookTankerRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/deliveries': typeof DeliveriesRoute
  '/my-orders': typeof MyOrdersRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/payments': typeof PaymentsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tankers': typeof TankersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-tanker': typeof BookTankerRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/deliveries': typeof DeliveriesRoute
  '/my-orders': typeof MyOrdersRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/payments': typeof PaymentsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tankers': typeof TankersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-tanker': typeof BookTankerRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/deliveries': typeof DeliveriesRoute
  '/my-orders': typeof MyOrdersRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/payments': typeof PaymentsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tankers': typeof TankersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-tanker'
    | '/complaints'
    | '/dashboard'
    | '/deliveries'
    | '/my-orders'
    | '/orders'
    | '/payment'
    | '/payments'
    | '/signin'
    | '/signup'
    | '/tankers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-tanker'
    | '/complaints'
    | '/dashboard'
    | '/deliveries'
    | '/my-orders'
    | '/orders'
    | '/payment'
    | '/payments'
    | '/signin'
    | '/signup'
    | '/tankers'
  id:
    | '__root__'
    | '/'
    | '/book-tanker'
    | '/complaints'
    | '/dashboard'
    | '/deliveries'
    | '/my-orders'
    | '/orders'
    | '/payment'
    | '/payments'
    | '/signin'
    | '/signup'
    | '/tankers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookTankerRoute: typeof BookTankerRoute
  ComplaintsRoute: typeof ComplaintsRoute
  DashboardRoute: typeof DashboardRoute
  DeliveriesRoute: typeof DeliveriesRoute
  MyOrdersRoute: typeof MyOrdersRoute
  OrdersRoute: typeof OrdersRoute
  PaymentRoute: typeof PaymentRoute
  PaymentsRoute: typeof PaymentsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TankersRoute: typeof TankersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tankers': {
      id: '/tankers'
      path: '/tankers'
      fullPath: '/tankers'
      preLoaderRoute: typeof TankersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-tanker': {
      id: '/book-tanker'
      path: '/book-tanker'
      fullPath: '/book-tanker'
      preLoaderRoute: typeof BookTankerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookTankerRoute: BookTankerRoute,
  ComplaintsRoute: ComplaintsRoute,
  DashboardRoute: DashboardRoute,
  DeliveriesRoute: DeliveriesRoute,
  MyOrdersRoute: MyOrdersRoute,
  OrdersRoute: OrdersRoute,
  PaymentRoute: PaymentRoute,
  PaymentsRoute: PaymentsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TankersRoute: TankersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
